#!/bin/bash

source usage 1 "usage: apply-configuration <database-configuration-path>" "$@"

database_configuration_path=$1

if [ ! -f $database_configuration_path ]; then
	source error "schemer: Configuration '$database_configuration_path' not found."
fi

source $database_configuration_path

if [ -z "$server" ]; then
	source error "schemer: \"server\" variable not defined in configuration. $host"
fi

if [ -z "$server_type" ]; then
	source error "schemer: \"server_type\" variable not defined in configuration. $host"
fi

if [ -z "$username" ]; then
	source error "schemer: \"username\" variable not defined in configuration."
fi

if [ ! -d ./connector/$server_type ]; then
	source error "schemer: Server type \"$server_type\" unsupported."
fi

if [ "$server_type" == "postgres" ]; then
	if [ -z "$postgres_database" ]; then
		source error "schemer: \"postgres_database\" variable not defined in configuration."
	fi
fi

