#!/bin/bash

set -e

./usage 1 "query <configuration-path>" "$@"

database_configuration_path=$1

source apply-configuration $database_configuration_path

psql \
	--dbname=$dbname \
	--host $host \
	--pset "format=unaligned" \
	--pset "tuples_only=on" \
	--quiet \
	--set "ON_ERROR_STOP=on" \
	--username $username
