#!/bin/bash

set -e

./usage 2 "dbvm versioning install <database-configuration-path> <schema>" "$@"

database_configuration_path=$1
schema=$2

if [ ! -f $database_configuration_path ]; then
	./error "dbvm: Database configuration '$database_configuration_path' not found."
fi

./dbvm-query $database_configuration_path << EOF
CREATE TABLE "$schema"."database_version"
(
	"id" INTEGER NOT NULL,
	"created" TIMESTAMP NOT NULL
);

ALTER TABLE "$schema"."database_version"
	ADD PRIMARY KEY ("id");

INSERT INTO "$schema"."database_version" VALUES (0, NOW());
EOF
