#!/bin/bash

set -e

usage() {
	echo "usage: dbvm [--version] <command> [<arguments>]"
	echo
	echo "Supported commands are:"
	echo "versioning   Manage versioning"
	echo
}

if [ $# -lt 1 ]; then
	usage >&2
	exit 1
fi

command=$1
cd $(dirname $(readlink -f $0))

case $command in
	versioning)
		./dbvm-versioning "${@:2}"
		;;

	--version)
		echo "dbvm version 0.1.0"
		exit 0
		;;

	*)
		echo "dbvm: '$command' is not a recognized command." >&2
		echo >&2
		usage >&2
		exit 1
esac
