#!/bin/bash

set -e

./usage 1 "dbvm manager uninstall <database-configuration-path>" "$@"

database_configuration_path=$1

source apply-configuration $database_configuration_path

./dbvm-query $database_configuration_path << EOF
DROP TABLE "$versioning_schema"."database_version";
EOF
