#!/bin/bash

set -e

usage() {
	echo "usage: dbvm versioning <command> [<arguments>]"
	echo
	echo "Supported commands are:"
	echo "install        Install versioning on database"
	echo "is-installed   Determine whether versioning is installed on database."
	echo "read           Read version of database"
	echo "uninstall      Uninstall versioning on database"
	echo
}

if [ $# -lt 1 ]; then
	usage >&2
	exit 1
fi

command=$1

case $command in
	install)
		./dbvm-versioning-install "${@:2}"
		;;

	is-installed)
		./dbvm-versioning-is-installed "${@:2}"
		;;

	read)
		./dbvm-versioning-read "${@:2}"
		;;

	uninstall)
		./dbvm-versioning-uninstall "${@:2}"
		;;

	*)
		echo "dbvm: '$command' is not a recognized command." >&2
		echo >&2
		usage >&2
		exit 1
esac
