#!/bin/bash

set -e

./usage 3 "dbvm version write <database-configuration-path> <schema> <version>" "$@"

database_configuration_path=$1
schema=$2
version=$3

./dbvm-query $database_configuration_path 2> /dev/null << EOF
INSERT INTO "$schema"."database_version" VALUES ($version, NOW());
EOF
