#!/bin/bash

set -e

./usage 2 "dbvm versioning uninstall <database-configuration-path> <schema>" "$@"

database_configuration_path=$1
schema=$2

if [ ! -f $database_configuration_path ]; then
	./error "dbvm: Database configuration '$database_configuration_path' not found."
fi

./dbvm-query $database_configuration_path << EOF
DROP TABLE "$schema"."database_version";
EOF
