#!/bin/bash

set -e

usage() {
	echo "usage: dbvm version <command> [<arguments>]"
	echo
	echo "Supported commands are:"
	echo "database-read    Read version of database"
	echo "database-write   Write version of database"
	echo
}

if [ $# -lt 1 ]; then
	usage >&2
	exit 1
fi

command=$1

case $command in
	database-read)
		./dbvm-version-database-read "${@:2}"
		;;

	database-write)
		./dbvm-version-database-write "${@:2}"
		;;

	*)
		echo "dbvm: '$command' is not a recognized command." >&2
		echo >&2
		usage >&2
		exit 1
esac
