#!/bin/bash

set -e

./usage 2 "dbvm backup restore <database-configuration-path> <backup-path>" "$@"

database_configuration_path=$1
backup_path=$2

if [ ! -f $backup_path ]; then
	./error "dbvm: Path \"$backup_path\" does not exist."
fi

./dbvm-query $database_configuration_path < $backup_path
