#!/bin/bash

set -e

./usage 2 "dbvm version read-database <database-configuration-path> <schema>" "$@"

database_configuration_path=$1
schema=$2

if [ ! -f $database_configuration_path ]; then
	./error "dbvm: Database configuration '$database_configuration_path' not found."
fi

version=$(./dbvm-query $database_configuration_path 2> /dev/null << EOF
SELECT MAX("id") FROM "$schema"."database_version";
EOF
)

echo $version
