#!/bin/bash

set -e

./usage 1 "schemer manager uninstall <database-configuration-path>" "$@"

database_configuration_path=$1

source apply-configuration $database_configuration_path
source connector-branch schemer-manager-uninstall
