#!/bin/bash

set -e

usage() {
	echo "usage: schemer backup <command> [<arguments>]"
	echo
	echo "Supported commands are:"
	echo "create    Create backup"
	echo "restore   Restore backup"
	echo
}

if [ $# -lt 1 ]; then
	source usage >&2
	exit 1
fi

command=$1

case $command in
	create)
		source schemer-backup-create "${@:2}"
		;;

	restore)
		source schemer-backup-restore "${@:2}"
		;;

	*)
		echo "schemer: '$command' is not a recognized command." >&2
		echo >&2
		usage >&2
		exit 1
esac
