#!/bin/bash

set -e

./usage 3 "schemer version write-database <database-configuration-path> <schema> <version>" "$@"

database_configuration_path=$1
schema=$2
version=$3

source apply-configuration $database_configuration_path
source connector-branch schemer-version-write-database $schema $version
