#!/bin/bash

set -eu

usage() {
	echo "usage: schemer [--version] <command> [<arguments>]"
	echo
	echo "Supported commands are:"
	echo "backup    Create backup"
	echo "create    Create schema"
	echo "restore   Restore backup"
	echo "update    Update schema"
	echo
}

if [ $# -lt 1 ]; then
	usage >&2
	exit 1
fi

command=$1

cd $(dirname $(readlink -f $0))

case $command in
	backup|\
	create|\
	destroy|\
	restore|\
	update)
		source schemer-$command "${@:2}"
		;;

	--version)
		echo "schemer version $(cat version)"
		;;

	*)
		echo "schemer: '$command' is not a recognized command." >&2
		echo >&2
		usage >&2
		exit 1
esac

