#!/bin/bash

source usage 3 "usage: schemer version update <database-configuration-path> <source-path> <schema-name>" "$@"

database_configuration_path=$1
source_path=$2
schema_name=$3

source apply-configuration $database_configuration_path

database_version=$(source schemer-version-read-database $database_configuration_path $schema_name)
source_version=$(source schemer-version-read-source $source_path)

echo "Database version: $database_version"
echo "Source version: $source_version"
echo

if [ $database_version -eq $source_version ]; then
	echo "Already up-to-date."
	echo
	exit 0
fi

if [ $database_version -gt $source_version ]; then
	source error "schemer: Database is ahead of source; cannot update."
fi

from=$(($database_version+1))
to=$source_version

for i in $(seq $from $to); do
	echo "Applying update #$i ($(readlink -f $source_path/$i*.sql))..."
	cat $source_path/$i*.sql | source connector-branch query-schema $schema_name
	source schemer-version-write-database $database_configuration_path $schema_name $i
done

echo
echo "Up-to-date."
echo
