#!/bin/bash

set -e

./usage 3 "schemer schema create <database-configuration-path> <schema-name> <schema-path>" "$@"

database_configuration_path=$1
schema_name=$2
schema_path=$3

if [ ! -d $schema_path ]; then
	./error "Path \"$schema_path\" not found."
fi

if [ ! -f $schema_path/.version ]; then
	./error "schemer: \".version\" file not present in \"$schema_path\"."
fi

if ! ./schemer manager is-installed $database_configuration_path; then
	./schemer manager install $database_configuration_path
fi

source apply-configuration $database_configuration_path
source connector-branch create-schema $schema_name

version=$(cat $schema_path/.version)

if [ -f $schema_path/.order ]; then
	echo "Found order file: \"$schema_path/.order\""
	echo

	order=$(cat $schema_path/.order)
else
	echo "Did not find .order file; defaulting to alphabetical order."
	echo

	order=$(ls -1 $schema_path | grep "\.sql$" | sort)
fi

while read -r path; do
	echo "Applying \"$path\"..."
	source connector-branch query < $schema_path/$path
done <<< "$order"

source connector-branch schemer-version-write-database $schema_name $version

echo
echo "Up-to-date."
echo
