#!/bin/bash

source usage 2 "schemer schema destroy <database-configuration-path> <schema-name>" "$@"

database_configuration_path=$1
schema_name=$2

source apply-configuration $database_configuration_path
source connector-branch schemer-schema-destroy

