#!/bin/bash

set -e

./usage 2 "schemer version write-database <database-configuration-path> <version>" "$@"

database_configuration_path=$1
version=$2

source apply-configuration $database_configuration_path

./schemer-query $database_configuration_path << EOF
INSERT INTO "$versioning_schema"."database_version" VALUES ($version, NOW());
EOF
