#!/bin/bash

set -e

usage() {
	echo "usage: schemer schema <command> [<arguments>]"
	echo
	echo "Supported commands are:"
	echo "create    Create schema"
	echo "destroy   Destroy schema"
	echo
}

if [ $# -lt 1 ]; then
	usage >&2
	exit 1
fi

command=$1

case $command in
	create)
		./schemer-schema-create "${@:2}"
		;;

	destroy)
		./schemer-schema-destroy "${@:2}"
		;;

	*)
		echo "schemer: '$command' is not a recognized command." >&2
		echo >&2
		usage >&2
		exit 1
esac
