#!/bin/bash

source usage 2 "usage: schemer backup <database-configuration-path> <backup-path>" "$@"

database_configuration_path=$1
backup_path=$2

source apply-configuration $database_configuration_path

if [ -f $backup_path ]; then
	source error "schemer: Refusing to overwrite previous backup \"$backup_path\"."
fi

touch $backup_path
chmod 600 $backup_path

source connector-branch create-backup

chmod 400 $backup_path

