#!/bin/bash

set -e

./usage 1 "schemer manager uninstall <database-configuration-path>" "$@"

database_configuration_path=$1

source apply-configuration $database_configuration_path

./query $database_configuration_path << EOF
DROP TABLE "$versioning_schema"."database_version";
EOF
