#!/bin/bash

set -eu

usage() {
	echo "usage: schemer [--version] <command> [<arguments>]"
	echo
	echo "Supported commands are:"
	echo "backup      Manage backups"
	echo "install     Install schemer to /usr/local/bin"
	echo "manager     Manage management"
	echo "schema      Manage schemas"
	echo "uninstall   Uninstall schemer from /usr/local/bin"
	echo "version     Manage versions"
	echo
}

if [ $# -lt 1 ]; then
	usage >&2
	exit 1
fi

command=$1
cd $(dirname $(readlink -f $0))

version=$(cat version)

case $command in
	backup)
		source schemer-backup "${@:2}"
		;;

	install)
		source schemer-install "${@:2}"
		;;

	manager)
		source schemer-manager "${@:2}"
		;;

	schema)
		source schemer-schema "${@:2}"
		;;

	uninstall)
		source schemer-uninstall "${@:2}"
		;;

	version)
		source schemer-version "${@:2}"
		;;

	--version)
		echo "schemer version $version"
		exit 0
		;;

	*)
		echo "schemer: '$command' is not a recognized command." >&2
		echo >&2
		usage >&2
		exit 1
esac

