#!/bin/bash

set -e

./usage 1 "schemer version read-source <source-path>" "$@"

source_path=$1

if [ ! -d $source_path ]; then
	./error "schemer: Source path '$source_path' not found."
fi

ls -1 $source_path |\
cut --delimiter='.' --fields=1 |\
cut --delimiter='_' --fields=1 |
sort --version-sort |
tail --lines=1
