#!/bin/bash

set -e

./usage 1 "schemer version read-database <database-configuration-path>" "$@"

database_configuration_path=$1

source apply-configuration $database_configuration_path

./query $database_configuration_path 2> /dev/null << EOF
SELECT MAX("id") FROM "$versioning_schema"."database_version";
EOF
