#!/bin/bash

source connector-branch query << EOF
CREATE SCHEMA IF NOT EXISTS "schemer" AUTHORIZATION "$username";

CREATE TABLE IF NOT EXISTS "schemer"."schema_version"
(
	"schema" TEXT NOT NULL,
	"version" INT NOT NULL,
	"created" TIMESTAMP NOT NULL,
	"deleted" TIMESTAMP
);
EOF

