#!/bin/bash

psql \
	--dbname=$postgres_database \
	--host $server \
	--pset "format=unaligned" \
	--pset "tuples_only=on" \
	--quiet \
	--set "ON_ERROR_STOP=on" \
	--single-transaction \
	--username $username
