#!/bin/bash

source usage 1 "write-version <schema-name> <version>" "$@"

schema_name=$1
version=$2

source connector-branch query << EOF
INSERT INTO "schemer"."schema_version" (
	"schema",
	"version",
	"created",
	"deleted")
VALUES (
	'$schema_name',
	$version,
	CURRENT_TIMESTAMP,
	NULL);

EOF

