#!/bin/bash

source connector-branch query << 'EOF'
CREATE DATABASE IF NOT EXISTS `schemer`;

CREATE TABLE IF NOT EXISTS `schemer`.`schema_version`
(
	`schema` VARCHAR(255) NOT NULL,
	`version` INTEGER NOT NULL,
	`created` DATETIME NOT NULL,
	`deleted` DATETIME
);
EOF

