#!/bin/bash

source usage 1 "read-version <schema-name>" "$@"

schema_name=$1

source connector-branch query << EOF
USE \`schemer\`;

SELECT COALESCE(MAX(\`version\`), -1)
FROM \`schema_version\`
WHERE \`schema\` = '$schema_name'
AND \`deleted\` IS NULL;

EOF

