#!/bin/bash

source usage 2 "write-version <schema-name> <version>" "$@"

schema_name=$1
version=$2

source connector-branch query << EOF
USE \`schemer\`;

INSERT INTO \`schema_version\` (
	\`schema\`,
	\`version\`,
	\`created\`,
	\`deleted\`)
VALUES (
	'$schema_name',
	$version,
	UTC_TIMESTAMP(),
	NULL);

EOF

